# Generated by Django 5.2.6 on 2025-09-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_goal_current_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
